CREATE TABLE users (
  id IDENTITY PRIMARY KEY,
  name VARCHAR NOT NULL UNIQUE
);

CREATE TABLE matches (
  id IDENTITY PRIMARY KEY,
  user1 INT NOT NULL,
  user2 INT NOT NULL,
  user1Hand VARCHAR NOT NULL,
  user2Hand VARCHAR NOT NULL
);
