CREATE TABLE IF NOT EXISTS users (
  id IDENTITY,
  name VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS matchinfo (
  id IDENTITY,
  user1 INT NOT NULL,
  user2 INT NOT NULL,
  user1_hand VARCHAR NOT NULL,
  is_active BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS matches (
  id IDENTITY,
  user1 INT NOT NULL,
  user2 INT NOT NULL,
  user1_hand VARCHAR NOT NULL,
  user2_hand VARCHAR NOT NULL,
  is_active BOOLEAN NOT NULL
);
